service:
  name: sumunara-deploy
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  region: ap-northeast-1
  runtime:  python3.8
  memorySize: 128
  logRetentionInDays: 1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  deploymentBucket:
    name: sumunara-deploy
  versionFunctions: false

functions:
  lambda_handler:
    handler: lambda_function.lambda_handler